name: Java CI

on:
  pull_request:
    branches:
      - master
      - preview
  push:
    branches:
      - master
      - preview

jobs:
  package:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package
        run: mvn --no-transfer-progress -DskipTests=true package

  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/arangodb:3.5.5
          - docker.io/arangodb/arangodb:3.6.5
          - docker.io/arangodb/arangodb:3.7.1
          - docker.io/arangodb/enterprise:3.5.5
          - docker.io/arangodb/enterprise:3.6.5
          - docker.io/arangodb/enterprise:3.7.1
        topology:
          - single
          - cluster

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start Database
        run: ./docker/start_db_${{ matrix.topology }}_retry_fail.sh ${{ matrix.docker-img }}
        env:
          ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
      - name: Test
        run: mvn --no-transfer-progress test
      - name: Debug containers
        if: ${{ cancelled() || failure() }}
        run: ./docker/debug_containers_${{ matrix.topology }}.sh
