name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - api-test
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - api-test

jobs:

  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/arangodb:3.10.13
          - docker.io/arangodb/arangodb:3.11.6
          - docker.io/arangodb/arangodb-preview:devel-nightly
          - docker.io/arangodb/enterprise:3.10.13
          - docker.io/arangodb/enterprise:3.11.6
          - docker.io/arangodb/enterprise-preview:devel-nightly
        topology:
          - single
          - cluster
          - activefailover
        db-ext-names:
          - false
        java-version:
          - 8
        user-language:
          - en
        exclude:
          - docker-img: docker.io/arangodb/arangodb-preview:devel-nightly
            topology: activefailover
          - docker-img: docker.io/arangodb/enterprise-preview:devel-nightly
            topology: activefailover

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'adopt'
          cache: maven
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
          STARTER_MODE: ${{matrix.topology}}
          DOCKER_IMAGE: ${{matrix.docker-img}}
          DATABASE_EXTENDED_NAMES: ${{matrix.db-ext-names}}
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn --no-transfer-progress test -DargLine="-Duser.language=${{matrix.user-language}}"

  # test encodeURIComponent() and normalize('NFC') comparing to Javascript behavior
  test-graalvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '11'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: 'js'
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn -e --no-transfer-progress test -Dtest=com.arangodb.util.UnicodeUtilsTest

  test-jwt:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/arangodb:3.11.6
        topology:
          - single
          - cluster
          - activefailover
        db-ext-names:
          - false
        java-version:
          - 17
        user-language:
          - en

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'adopt'
          cache: maven
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
          STARTER_MODE: ${{matrix.topology}}
          DOCKER_IMAGE: ${{matrix.docker-img}}
          DATABASE_EXTENDED_NAMES: ${{matrix.db-ext-names}}
      - name: Set JWT
        run: |
          ENDPOINT=$(./docker/find_active_endpoint.sh)
          echo "Active endpoint: $ENDPOINT"
          JWT=$(curl "http://$ENDPOINT/_db/_system/_open/auth" -X POST -d '{"username":"root","password":"test"}' | jq ".jwt" | xargs)
          echo "Setting JWT: $JWT"
          sed -i "/arangodb.password/c\arangodb.jwt=$JWT" src/test/resources/arangodb.properties
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn --no-transfer-progress test -DargLine="-Duser.language=${{matrix.user-language}}"

